"""'initializedb'

Revision ID: a7e25b669ad4
Revises: 
Create Date: 2016-09-04 20:19:06.715044

"""

# revision identifiers, used by Alembic.
revision = 'a7e25b669ad4'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=64), nullable=True),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('password', sa.Unicode(length=60), nullable=True),
    sa.Column('email', sa.Unicode(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_authenticated', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('signup', sa.DateTime(), nullable=True),
    sa.Column('api_key', sa.Unicode(length=12), nullable=True),
    sa.Column('invite_ct', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activations',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('code', sa.Unicode(length=60), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('tasks',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('username', sa.Unicode(length=255), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('activations')
    op.drop_table('users')
    ### end Alembic commands ###
